# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19994ea95e09c5b665272726c55633a57e7d323e063a90b458bf8d390f74fb60e89f1f6d9cce1d8af65daf8eadf93f3dcc685ab7f6c2b9bc7ab87cf553370f93

test:
  secret_key_base: 9fbb6ebdd94007ddbdb9cd1f866dc716f17863ecccdc9cd5a110e266c8c308877d50a32f74a7404bf67f4642784ab6a00b26d4319418e8deac7dc20a495b8249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
